# Generated by Django 6.1.1 on 2026-10-02 12:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assigned_to',
            field=models.ForeignKey(blank=True, help_text='The doctor/nurse this user is assigned to', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_users', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='specialty',
            field=models.CharField(blank=True, help_text='For doctors: e.g. Cardiology, Radiology', max_length=100),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('UPLOAD', 'Upload'), ('VIEW', 'View'), ('DOWNLOAD', 'Download'), ('SHARE', 'Share'), ('ACCESS_REVOKED', 'Access Revoked'), ('DELETE', 'Delete'), ('ACCESS_REQUEST', 'Access Request'), ('ACCESS_APPROVED', 'Access Approved'), ('ACCESS_REJECTED', 'Access Rejected'), ('ASSIGNED', 'Assigned')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('DOCTOR', 'Doctor'), ('NURSE', 'Nurse'), ('PATIENT', 'Patient')], default='PATIENT', max_length=20),
        ),
    ]
