/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashRouteImport } from './routes/_dash'
import { Route as AboutRouteImport } from './routes/about'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as DashActivityRouteImport } from './routes/_dash.activity'
import { Route as DashDashboardRouteImport } from './routes/_dash.dashboard'
import { Route as DashFilesRouteImport } from './routes/_dash.files'
import { Route as DashPatientsRouteImport } from './routes/_dash.patients'
import { Route as DashProfileRouteImport } from './routes/_dash.profile'
import { Route as DashSharedRouteImport } from './routes/_dash.shared'
import { Route as DashUploadRouteImport } from './routes/_dash.upload'
import { Route as DashDocumentsIdRouteImport } from './routes/_dash.documents.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashRoute = DashRouteImport.update({
  id: '/_dash',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DashActivityRoute = DashActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => DashRoute,
} as any)
const DashDashboardRoute = DashDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => DashRoute,
} as any)
const DashFilesRoute = DashFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => DashRoute,
} as any)
const DashPatientsRoute = DashPatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => DashRoute,
} as any)
const DashProfileRoute = DashProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashRoute,
} as any)
const DashSharedRoute = DashSharedRouteImport.update({
  id: '/shared',
  path: '/shared',
  getParentRoute: () => DashRoute,
} as any)
const DashUploadRoute = DashUploadRouteImport.update({
  id: '/upload',
  path: '/upload',
  getParentRoute: () => DashRoute,
} as any)
const DashDocumentsIdRoute = DashDocumentsIdRouteImport.update({
  id: '/documents/$id',
  path: '/documents/$id',
  getParentRoute: () => DashRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/activity': typeof DashActivityRoute
  '/dashboard': typeof DashDashboardRoute
  '/files': typeof DashFilesRoute
  '/patients': typeof DashPatientsRoute
  '/profile': typeof DashProfileRoute
  '/shared': typeof DashSharedRoute
  '/upload': typeof DashUploadRoute
  '/documents/$id': typeof DashDocumentsIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/activity': typeof DashActivityRoute
  '/dashboard': typeof DashDashboardRoute
  '/files': typeof DashFilesRoute
  '/patients': typeof DashPatientsRoute
  '/profile': typeof DashProfileRoute
  '/shared': typeof DashSharedRoute
  '/upload': typeof DashUploadRoute
  '/documents/$id': typeof DashDocumentsIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_dash': typeof DashRouteWithChildren
  '/about': typeof AboutRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_dash/activity': typeof DashActivityRoute
  '/_dash/dashboard': typeof DashDashboardRoute
  '/_dash/files': typeof DashFilesRoute
  '/_dash/patients': typeof DashPatientsRoute
  '/_dash/profile': typeof DashProfileRoute
  '/_dash/shared': typeof DashSharedRoute
  '/_dash/upload': typeof DashUploadRoute
  '/_dash/documents/$id': typeof DashDocumentsIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/features'
    | '/login'
    | '/register'
    | '/activity'
    | '/dashboard'
    | '/files'
    | '/patients'
    | '/profile'
    | '/shared'
    | '/upload'
    | '/documents/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/features'
    | '/login'
    | '/register'
    | '/activity'
    | '/dashboard'
    | '/files'
    | '/patients'
    | '/profile'
    | '/shared'
    | '/upload'
    | '/documents/$id'
  id:
    | '__root__'
    | '/'
    | '/_dash'
    | '/about'
    | '/features'
    | '/login'
    | '/register'
    | '/_dash/activity'
    | '/_dash/dashboard'
    | '/_dash/files'
    | '/_dash/patients'
    | '/_dash/profile'
    | '/_dash/shared'
    | '/_dash/upload'
    | '/_dash/documents/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashRoute: typeof DashRouteWithChildren
  AboutRoute: typeof AboutRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash': {
      id: '/_dash'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof DashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_dash/activity': {
      id: '/_dash/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof DashActivityRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/dashboard': {
      id: '/_dash/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashDashboardRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/files': {
      id: '/_dash/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof DashFilesRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/patients': {
      id: '/_dash/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof DashPatientsRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/profile': {
      id: '/_dash/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof DashProfileRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/shared': {
      id: '/_dash/shared'
      path: '/shared'
      fullPath: '/shared'
      preLoaderRoute: typeof DashSharedRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/upload': {
      id: '/_dash/upload'
      path: '/upload'
      fullPath: '/upload'
      preLoaderRoute: typeof DashUploadRouteImport
      parentRoute: typeof DashRoute
    }
    '/_dash/documents/$id': {
      id: '/_dash/documents/$id'
      path: '/documents/$id'
      fullPath: '/documents/$id'
      preLoaderRoute: typeof DashDocumentsIdRouteImport
      parentRoute: typeof DashRoute
    }
  }
}

interface DashRouteChildren {
  DashActivityRoute: typeof DashActivityRoute
  DashDashboardRoute: typeof DashDashboardRoute
  DashFilesRoute: typeof DashFilesRoute
  DashPatientsRoute: typeof DashPatientsRoute
  DashProfileRoute: typeof DashProfileRoute
  DashSharedRoute: typeof DashSharedRoute
  DashUploadRoute: typeof DashUploadRoute
  DashDocumentsIdRoute: typeof DashDocumentsIdRoute
}

const DashRouteChildren: DashRouteChildren = {
  DashActivityRoute: DashActivityRoute,
  DashDashboardRoute: DashDashboardRoute,
  DashFilesRoute: DashFilesRoute,
  DashPatientsRoute: DashPatientsRoute,
  DashProfileRoute: DashProfileRoute,
  DashSharedRoute: DashSharedRoute,
  DashUploadRoute: DashUploadRoute,
  DashDocumentsIdRoute: DashDocumentsIdRoute,
}

const DashRouteWithChildren = DashRoute._addFileChildren(DashRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashRoute: DashRouteWithChildren,
  AboutRoute: AboutRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
